spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates: 
           - Path=/order/**
          filters:
           - name: CircuitBreaker
             args:
              name: orderServiceCircuitBreaker
              fallbackUri: forward:/orderFallBack
        - id: payment-service
          uri: lb://payment-service
          predicates: 
            - Path=/payment/**
          filters:
           - name: CircuitBreaker
             args:
              name: paymentServiceCircuitBreaker
              fallbackUri: forward:/paymentFallBack
server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
