eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
               preferIpAddress: true     
               hostname: localhost
  
  
spring:
   application:
              name: gateway-service
   h2:
      console:
              enabled: true
  
server:
      port: 9092


management:
           endpoints: 
                    web: 
                        exposure:
                                  include: hystrix.stream
  