spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
  cloud:
    config:
      uri:
        - http://localhost:9093
server:
  port: 9091
logging:
    file:
        path: E:/logs/microservice