eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
               preferIpAddress: true     
               hostname: localhost
  
  
spring:
   application:
              name: payment-service
   h2:
      console:
              enabled: true
  
server:
      port: 9091
      
 