spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
  zipkin:    base-url: http://localhost:9411/
server:
  port: 9090

logging:
    file:
        path: E:/logs/microservice 