spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/Ratna1992/spring-cloud-config-server'
server:
  port: 9093
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    preferIpAddress: true
    hostname: localhost
